### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by DanielHaze** [v1k45/python-qBittorrent#13]
I had my staff working with qbittorrent and python-qbittorrent, it only scrapped some website and donwload torrents of my interest. But now I'm getting this error:

his wrapper only supports qBittorrent applications
                 with version higher than 3.1.x.
                 Please use the latest qBittorrent release.

I have installed the 3.3.6 version of qbittorrent, the 2.7.11 version of python and the 0.1.8 version of python-qbittorrent. I have done serveral upgrades and downgrades but nothing seems to work for me, any idea on how can I solve this problem?

Thanks a lot

**Comment by v1k45** [comment]
Hey @DanielHaze , this exception was introduced to alert users that they are using the wrong version of qbittorrent client. It is strange that you are seeing this error on a latest release.

You said your staff was working with it and was able to download torrents before, are you seeing this error only on your machine or am I missing something?

**Comment by v1k45** [comment]
Closing this issue as no response was received from submitter for more than 6 months.
