### ISSUE TITLE
API calls fails unless referrer is provided

### ISSUE THREAD

**Issue by kryksyh** [v1k45/python-qBittorrent#19]
Hi!
I am trying to use this module, but it doesn't work with qBittorrent 3.3.13 on Archlinux x64. All API calls fails unless I specify referrer like this:
```python
        self.session = requests.Session()
        header = {
            'Referer': 'http://localhost:8080'
        }
        login = self.session.post(self.url+'login',
                                  data={'username': username,
                                        'password': password},
                                  headers=header)
        if login.text == 'Ok.':
            self._is_authenticated = True
        else:
            return login.text
```

I have no experience with qBittorrent, is it my misconfiguration or is it some API update and should be fixed in this library?

python: 3.6.0
requests: 2.18.1

**Comment by v1k45** [comment]
Sorry for the late reply. I'll try to reproduce this and let you know.

**Comment by v1k45** [comment]
Hey, I am not able to reproduce this issue. The module works fine without the Referer header.

What do you mean when you say "failed"? What error message are you receiving?

**Comment by teejo75** [comment]
https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#changes

Note that as of API14, referrer is required on all API calls. (qBittorrent 3.20+)

**Comment by v1k45** [comment]
Thanks @teejo75 I'll push a fix for his ASAP.

**Comment by kmlucy** [comment]
Did this ever get fixed?

**Comment by teejo75** [comment]
Yes it did.

**Comment by the-white-light** [comment]
@kmlucy It works fine for me with qb4.1.4, so presumably yes.
