### ISSUE TITLE
Pre-requisite

### ISSUE THREAD

**Issue by Jambon1510** [v1k45/python-qBittorrent#20]
Do you mind adding a prerequisite section in your documentation mentioning webUI needs to be activated (how to: https://github.com/lgallard/qBittorrent-Controller/wiki/How-to-enable-the-qBittorrent-Web-UI)
?

I was having this issue and struggle for 10 min before understanding that it was not activated by default

`equests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /query/preferences (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4b0225a20>: Failed to establish a new connection: [Errno 111] Connection refused',))
`

**Comment by v1k45** [comment]
Thanks @Jambon1510 . I've added a prerequisite section.
