### ISSUE TITLE
qb.download_from_link doesn't work with Lists

### ISSUE THREAD

**Issue by faulander** [v1k45/python-qBittorrent#21]
Qbittorrent: 4.0.4
OS: Windows 10
Python: 2.7

Downloadlist is a list populated with a few items.
Category is "Movies" in this case.
I always get into the Except-State.

`if len(Downloadlist)>0:

    try:

        qb.download_from_link(Downloadlist, category=category)

        for i in Downloadlist:

            completed.append(i)

            print("Added: ", i)

    except:

        print("Download could not be added to qBittorrent\n")
`

**Comment by faulander** [comment]
No feedback?

**Comment by v1k45** [comment]
Sorry @faulander I totally forgot about this. Will try to reproduce this issue later today.

**Comment by cheenar** [comment]
@faulander submitted a pull request that fixes this issue (if you are still interested).

**Comment by zeroone2numeral2** [comment]
I guess this can be closed because of 04f9482, right?
