### ISSUE TITLE
Get download percentage

### ISSUE THREAD

**Issue by SamanHamidi** [v1k45/python-qBittorrent#24]
Hey there, 

I wrote a little code that would automatically download a bunch of torrents. I'm using python-qbittorrent. I was wondering is there a way I can get the download percentage as an output when a new download is started? I read the docs but I fail to find anything that would return this value. 

Any help would be appreciated.

**Comment by the-white-light** [comment]
Take a look here: https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#get-torrent-list
That is the info returned by `qb.torrents()` as a `list` of `dict`. You want `torrent["progress"]`.
