### ISSUE TITLE
I can't import the package normally.

### ISSUE THREAD

**Issue by Warm-rain** [v1k45/python-qBittorrent#29]
python-qbittorrent 0.31
python 3.7.1

`Traceback (most recent call last):
  File "G:/1python/qbittorrent.py", line 1, in <module>
    from qbittorrent import Client
  File "G:\1python\qbittorrent.py", line 1, in <module>
    from qbittorrent import Client
ImportError: cannot import name 'Client' from 'qbittorrent' (G:\1python\qbittorrent.py)
`

![image](https://user-images.githubusercontent.com/31696282/57309037-efa1f300-7119-11e9-9503-2fa1e4bafa97.png)

Thank you for helping me.

**Comment by DEADSEC-SECURITY** [comment]
Do you have it installed?
