### ISSUE TITLE
Incompatible with 'Bypass authentication for localhost' option in qBittorrent

### ISSUE THREAD

**Issue by dsemi** [v1k45/python-qBittorrent#3]
In the WebUI options for qBittorrent, there is an option to bypass authentication if the requests come from localhost.  If this option is enabled, any requests from localhost do not have to authenticate before making requests; e.g. I should be able to GET /query/torrents without first POSTing to /login.
Right now, without calling Client#login, calling Client#torrents will raise a LoginRequired error when I shouldn't need any authentication as the request is coming from my local machine.

**Comment by v1k45** [comment]
Hi @dsemi ,
I'll fix it ASAP :)

**Comment by dsemi** [comment]
Thanks for the quick response!

**Comment by v1k45** [comment]
Fixed it.

```
In [1]: from qbittorrent.client import Client

In [2]: qb = Client('http://127.0.0.1:8080')

In [3]: qb._is_authenticated
Out[3]: True

In [4]: qb.logout()
Out[4]: {}

In [5]: qb._is_authenticated
Out[5]: False

```

Will update the PyPI package soon :)
