### ISSUE TITLE
Expiring authentication is not handled

### ISSUE THREAD

**Issue by TnS-hun** [v1k45/python-qBittorrent#30]
The authentication cookie expires after a while, and after that API calls fail. python-qBittorrent should handle the reauthentication.

To reproduce the problem:
1. make any API calls, and notice that it works
2. sleep for an hour
3. make the same API call, and notice that it fails with 403 Client Error: Forbidden for url

**Comment by DEADSEC-SECURITY** [comment]
Check if this fixed the issue:
https://github.com/v1k45/python-qBittorrent/pull/63

**Comment by DEADSEC-SECURITY** [comment]
Solved by #64
