### ISSUE TITLE
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080)

### ISSUE THREAD

**Issue by shahrooz97** [v1k45/python-qBittorrent#32]
When trying to make a local connection get this error

qb = Client('http://127.0.0.1:8080/')

ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /query/preferences (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x77148fc128>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by shahrooz97** [comment]
I'm using python 3.7 on termux Android

**Comment by VictorZuanazzi** [comment]
I have the exact same problem. Any solutions?

**Comment by v1k45** [comment]
Make sure you are running qBittorrent and the WEB UI and API feature are enabled.

**Comment by martinetmayank** [comment]
> Make sure you are running qBittorrent and the WEB UI and API feature are enabled.

So, I must have qBitorrent client installed in my system?

**Comment by Sonic3R** [comment]
Of course you should have
