### ISSUE TITLE
Events handling

### ISSUE THREAD

**Issue by shivamdev-lgtm** [v1k45/python-qBittorrent#33]
It'd be very handy to have an event system which would automatically call functions on various events like on_download_started, on_download_progress, on_download_complete, on_download_error, if possible

**Comment by zeroone2numeral2** [comment]
@lzzy12 where are these events documented? I cannot find anything about that in [qbitorrent's web API documentation](https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation)

**Comment by v1k45** [comment]
This isn't document anywhere and seems to be out of scope for this library. python-qbittorrent is only intended to be used as a API client.
