### ISSUE TITLE
Login fails under qBittorrent 3.1.11

### ISSUE THREAD

**Issue by stumpylog** [v1k45/python-qBittorrent#4]
Following the example labeled "Quick Usage Guide" results in an exception.
python-qbittorrent version: 0.1.4
qBittorrent version 3.1.11
requests version 2.8.1

Traceback:
Traceback (most recent call last):
  File "./temp.py", line 13, in <module>
    torrents = qb.torrents()
  File "/usr/local/lib/python2.7/dist-packages/qbittorrent/client.py", line 168, in torrents
    return self._get('query/torrents', params=params)
  File "/usr/local/lib/python2.7/dist-packages/qbittorrent/client.py", line 34, in _get
    return self._request(endpoint, 'get', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/qbittorrent/client.py", line 62, in _request
    raise LoginRequired
qbittorrent.client.LoginRequired: Please login first.

The Web UI is enabled in preferences, accessible with a browser and the username/password combination works in the browser.  I have also tested with different passwords, and bypassing authentication for localhost.  All these have the same result.

Looking at the login code, and replicating it with requests directly, 

> session = requests.Session()
> login = session.post('http://127.0.0.1:8080/login', data={'username': 'admin', 'password': 'admin'})
> print login.status_code

results in a status code of '404'.  If there's more info that would be helpful, let me know.

**Comment by v1k45** [comment]
The api wrapper is intended to work only on versions above 3.1.x. Please try [mookfist's repo](https://github.com/mookfist/python-qbittorrent).

**Comment by ryee1** [comment]
I am using v3.1.11 qbittorrent and receiving the same issue.

Traceback (most recent call last):
  File "/home/test.py", line 6, in <module>
    torrents = qb.torrents()
  File "/usr/local/lib/python3.4/dist-packages/qbittorrent/client.py", line 168, in torrents
    return self._get('query/torrents', params=params)
  File "/usr/local/lib/python3.4/dist-packages/qbittorrent/client.py", line 34, in _get
    return self._request(endpoint, 'get', **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/qbittorrent/client.py", line 62, in _request
    raise LoginRequired
qbittorrent.client.LoginRequired: Please login first.

```
from qbittorrent import Client

qb = Client('http://127.0.0.1:8080')
qb.login('admin','password')

torrents = qb.torrents()
```

**Comment by v1k45** [comment]
Hi @ryee1 , as said above, it won't work on 3.1.x. You either have to upgrade to latest 3.3.x or use [this repo](https://github.com/mookfist/python-qbittorrent)

You can get the latest version of qbittorrent [on this page](http://www.qbittorrent.org/download.php).

**Comment by seeker** [comment]
How about checking the api version during init and throwing an exception if it is too low (or a 404 is returned)?

**Comment by v1k45** [comment]
@dozedoff , nice idea. I'll work on this soon :)

**Comment by eliabntt** [comment]
Hi try 
`pip install python-qbittorrent --upgrade`
if output says  `Found existing installation: requests 2.2.1  Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS`
delete and retry first `pip install python-qbittorrent --upgrade` than try your code

**Comment by eliabntt** [comment]
@v1k45 i have to attatch qb.login(us, pw) to let your program work even if i have free access from localhost

**Comment by v1k45** [comment]
Hi @eliabntt,

> Found existing installation: requests 2.2.1 Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS

This behavior is totally okay as PIP says that you already have all requirements installed, no need to upgrade them.

> i have to attatch qb.login(us, pw) to let your program work even if i have free access from localhost

What version of qBittorrent you're using? On what platform? Does `qb.login(us, pw)` work for you or it throws any error/exception?

**Comment by eliabntt** [comment]
> This behavior is totally okay as PIP says that you already have all requirements installed, no need to upgrade them. 

I've got the same issue yesterday and the pip update library in /usr/local/bin but the OS's ones has precedence 
Anyway it work for me I've deleted that folder and than do the upgrade so all works well
Ubuntu 14.04.3 for or odroid c1+, qbittorrent 3.1.11, so it should work well as you write on first page of this report

> for qBittorrent Web API (for versions above v3.1.x).

anyway I can't update on 3.3.x because no stable version for armhf were released and not stable version don't work I've tried every single method.
qb.login() seems work(I'm not 100% sure) but I have set qbittorrent to bypass login on localhost and this work on browser but not with library. 

> not required when 'Bypass from localhost' setting is active.

**Comment by v1k45** [comment]
>  for qBittorrent Web API (for versions above v3.1.x).

This is being misinterpreted by many folks. By above 3.1.x, i mean any version that starts with 3.1 won't work. This happens because the authentication method was changed to session based after versions above 3.1.

You have to either update your qBittorrent client  (the newer versions have loads of awesome features :) ) or use mookfist's version of qBittorrent python wrapper.

**Comment by eliabntt** [comment]
It works well with your lib
Il 08/giu/2016 08:28 AM, "Vikas" notifications@github.com ha scritto:

**Comment by v1k45** [comment]
Are you sure that it works? Are you able to perform other actions like extracting list of torrents, adding etc?

**Comment by eliabntt** [comment]
I've extracted successfully my list of torrents ;)
Il 08/giu/2016 08:31 AM, "Vikas" notifications@github.com ha scritto:

**Comment by eliabntt** [comment]
I'll keep you informed
Il 08/giu/2016 08:32 AM, "Elia Bonetto" eliabntt94@gmail.com ha scritto:

**Comment by v1k45** [comment]
Thats something I wasn't expecting. I'll test the client with 3.1.11 as soon as I get time. Thanks :)
