### ISSUE TITLE
This wrapper only supports qBittorrent applications with version higher than 4.1.x. Please use the latest qBittorrent release.

### ISSUE THREAD

**Issue by AsifAhmedShodip** [v1k45/python-qBittorrent#51]
This wrapper only supports qBittorrent applications with version higher than 4.1.x. Please use the latest qBittorrent release.

**Comment by DEADSEC-SECURITY** [comment]
Can you please close this @AsifAhmedShodip. This is not a issue, its a statement, if you want to add this to the docs please open a PR
