### ISSUE TITLE
download with SequentialDownload

### ISSUE THREAD

**Issue by pilsnerbeer** [v1k45/python-qBittorrent#53]
improvement proposal: there should be a way to toggle sequential download when adding torrent initially from `download_from_link` , like `download_from_link(file, savepath, sequential=True)`., like with qbit GUI client. The reason is that there is a delay when adding a torrent to download, so when `download_from_link` is called followed immediately with `toggle_sequential_download`, the torrent may not have been initialized yet, so the toggle is simply ignored.

**Comment by DEADSEC-SECURITY** [comment]
Why don't you toggle first and then init the download?
