### ISSUE TITLE
how to wait untill download is finished

### ISSUE THREAD

**Issue by furjac** [v1k45/python-qBittorrent#57]
plz help me with this wait untill download finished and do something
torrent_file = open('game.torrent', 'rb')
qb.download_from_file(torrent_file, save_path=os.getcwd())
d = qb.torrents()
for torrent in d:
    name = torrent['name']
    hash = torrent['hash']

now how to print download progress 
or wait untill download is finished

**Comment by DEADSEC-SECURITY** [comment]
You can do a loop and every n seconds check if its downloaded.

QBittorent doesn't have a WS api endpoint so this is the closest to live your getting.

You can also try the notify at download end function of QBittorent.
