### ISSUE TITLE
Change URL Login

### ISSUE THREAD

**Issue by felipeadeildo** [v1k45/python-qBittorrent#59]
On `qbittorrent.Client.__init__` line 31 change

From: `prefs_url = self.url + 'app/preferences'`
To: `prefs_url = self.url + 'auth/login'`

This change is nescessary to login in new versions of the qbittorrent webUI

**Comment by DEADSEC-SECURITY** [comment]
Does this fix it?
https://github.com/v1k45/python-qBittorrent/pull/63

**Comment by felipeadeildo** [comment]
Yes, thanks!
