### ISSUE TITLE
Unsupported Media Type error when attempting to download_from_file

### ISSUE THREAD

**Issue by jerblack** [v1k45/python-qBittorrent#6]
We got past the last error, but now I'm getting a new one

``` python
tor = r"C:\Torrents\add_torrent\sample2.torrent"
f = open(tor)
o.qb.download_from_file(f, label='comics')
```

This gives the following error

``` python
Traceback (most recent call last):
  File "C:\Torrents\utilities\qbittorrent_port_updater.py", line 115, in <module>
    start()
  File "C:\Torrents\utilities\qbittorrent_port_updater.py", line 43, in start
    nt.check(o)
  File "C:\Torrents\utilities\qbittorrent_port_updater.py", line 98, in check
    o.qb.download_from_file(f, label='comics')
  File "C:\Python27\lib\site-packages\qbittorrent\client.py", line 325, in download_from_file
    return self._post('command/upload', data=data, files=torrent_files)
  File "C:\Python27\lib\site-packages\qbittorrent\client.py", line 46, in _post
    return self._request(endpoint, 'post', data, **kwargs)
  File "C:\Python27\lib\site-packages\qbittorrent\client.py", line 70, in _request
    request.raise_for_status()
  File "C:\Python27\lib\site-packages\requests\models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 415 Client Error: Unsupported Media Type for url: http://torrent:8080/command/upload
```

**Comment by v1k45** [comment]
It appears to be qbittorrent server-specific error. Does that file works when directly added in qbittorrent GUI client?

**Comment by jerblack** [comment]
The torrent file does work when just dragged in.

It seems like other instances of that error I found online related to not having the correct Content-Type set. I was looking through the code and I can't see where you are setting the Content-Type for this POST. According to the link below, the Content-Type should be "application/x-bittorrent":

https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#upload-torrent-from-disk

**Comment by v1k45** [comment]
The content-type `application/x-bittorrent` is the [MIME-Type](https://en.wikipedia.org/wiki/MIME) of the torrent file. Every torrent file is supposed to have it in its headers. And it automatically set as content-type when doing web uploads.

The most probable cause of the error is that you're generating these torrents by yourself or are using outdated tools. Almost every torrent file has this MIME Type.

You can check the MIME of the file you are trying using this [SO Answer](http://stackoverflow.com/a/2133843/4726598)

**Comment by v1k45** [comment]
Also, you're getting this error for every file or just a specific file?

**Comment by jerblack** [comment]
Nope on all accounts. I just downloaded a new torrent file from kat.cr and tested with that, and I got the same error. I have the newest version of qbittorrent (3.3.3), requests, and your wrapper.

**Comment by v1k45** [comment]
I tried this with a latest KAT torrent, it works.

here's the code

```
In [6]: f = r"/home/my-username/Downloads/[kat.cr]the.test.download.600mb.torrent"

In [7]: ff = open(f)

In [8]: qb = Client("http://127.0.0.1:8080")

In [9]: qb.download_from_file(ff, label="movies")
Out[9]: {}

In [10]: 

```

PS: I am using 3.3.1 on Linux, I'll try with the latest version on windows ASAP.

**Comment by jerblack** [comment]
Also, I am using Python 2.7.11 if that matters

**Comment by v1k45** [comment]
It appears that the file handling was changed in 3.3.2. Will look into the matter in few hours.

**Comment by v1k45** [comment]
Hi @jerblack ,
I tried to replicate the issue on Windows with qBittorrent 3.3.3.

This exception is only raised when you open your file in 'r' mode. When opening the file with 'rb' mode, the same wrapper with no modifications works.

Here is an example code:

``` python
from qbittorrent import Client

qb = Client("http://127.0.0.1:8080")

print qb.api_version
# will return 8, 3.3.1 has 7

f = "C:\Users\VIKAS\Downloads\[kat.cr]the.example.file.torrent"

qb.download_from_file(open(f, 'rb'))

```

I'll update the docs and code to make sure no one encounters this problem again :)

**Comment by v1k45** [comment]
Hi @jerblack , I've update the docs (see 072756e51c88ca58a5a3b14d2087e101afa4875f).

Please reply if you're satisfied or not with the answer so that I can close the issue.

**Comment by jerblack** [comment]
I just had a chance to test and your fixes worked. I updated my code to open the file in 'rb' mode and updated the client.py to the latest one from here, and now everything seems to be working. Much appreciated! Thanks!
