### ISSUE TITLE
force_start default value is incorrect

### ISSUE THREAD

**Issue by jerblack** [v1k45/python-qBittorrent#7]
The default for the value parameter is not correct. Currently it is set to the Python Boolean True, but it should just be set to the string "true" since that is the text the setForceStart endpoint is [expecting](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#set-force-start). I had to make the change in my local copy of client.py to make force_start work.

``` python
    def force_start(self, infohash_list, value=True):
```

should be

``` python
    def force_start(self, infohash_list, value="true"):
```

**Comment by v1k45** [comment]
No need to pass string value for boolean, works just like before.

``` python
instance.force_start('....INFO_HASH...', True)
instance.force_start('....INFO_HASH...', False)
```

**Comment by jerblack** [comment]
It didn't work for me until I changed it to pass a string.

**Comment by v1k45** [comment]
Have you updated the code in your local machine?

You replied this via email, so I am guessing you didn't check the commit to fix this.
